services:
  chatbot:
    build: .
    image: inpe-chatbot-local:1.0
    container_name: nimchat
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs
      - ./user_data:/app/user_data